# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2341903eda33f3b851fc31f95aefe3794793df24838466c4c4df70cc45a26805859e6c8e07ef0e9f31d49690f634e4ee0cd9cac041e298f807f7c6221aa4edf5

test:
  secret_key_base: b0258becbc1735595b2d7125c87905104915cb1641484aa01479db1cbc213c7ad65c295cddee174db81a38e042421386fe735e3343fab664574d63ff887eb7f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
